# Generated by Django 4.0.3 on 2022-03-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
    ]
