# Generated by Django 4.0.3 on 2022-03-26 21:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todolist', '0002_auto_20220326_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
                ('tagColor', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('taskBigName', models.CharField(max_length=200)),
                ('taskDone', models.BooleanField(default=False)),
                ('taskNote', models.TextField(blank=True)),
                ('taskStartDate', models.DateField(blank=True)),
                ('taskStartTime', models.TimeField(blank=True)),
                ('taskEndDate', models.DateField(blank=True)),
                ('taskEndTime', models.TimeField(blank=True)),
                ('taskTags', models.ManyToManyField(blank=True, to='todolist.tag')),
            ],
        ),
    ]
