# Generated by Django 4.0.3 on 2022-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_listitem_taskdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='taskDeadLine',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskNote',
            field=models.TextField(null=True),
        ),
    ]
