# Generated by Django 4.0.3 on 2022-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_listitem_taskdeadline_alter_listitem_tasknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='taskDeadLine',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskNote',
            field=models.TextField(blank=True),
        ),
    ]
