# Generated by Django 4.0.3 on 2022-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_listitem_taskdeadline_alter_listitem_tasknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='taskDeadLine',
            field=models.DateField(),
        ),
    ]
