# Generated by Django 4.0.3 on 2022-04-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_rename_taskdone_listitem_task_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='task_tags',
        ),
        migrations.AddField(
            model_name='listitem',
            name='task_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.tag'),
        ),
    ]
