# Generated by Django 4.0.3 on 2022-03-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_listitem_taskdeadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='taskDeadLine',
            new_name='taskDeadline',
        ),
    ]
