# Generated by Django 4.0.3 on 2022-04-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_listitem_task_tags_listitem_task_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.user'),
        ),
    ]
