# Generated by Django 4.0.3 on 2022-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_listitem_tasktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='taskTag',
        ),
        migrations.AddField(
            model_name='listitem',
            name='taskTag',
            field=models.ManyToManyField(to='todolist.tag'),
        ),
    ]
