# Generated by Django 4.0.3 on 2022-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_tag_remove_listitem_tasktag_listitem_tasktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='taskTags',
            field=models.ManyToManyField(to='todolist.tag'),
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='taskTag',
        ),
        migrations.AddField(
            model_name='listitem',
            name='taskTag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
