# Generated by Django 4.0.3 on 2022-03-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_listitem_tasktags_remove_listitem_tasktag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='taskTag',
        ),
    ]
