# Generated by Django 4.0.3 on 2022-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_alter_listitem_tasktags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='taskStarDate',
            field=models.DateField(auto_now=True),
        ),
    ]
