# Generated by Django 4.0.3 on 2022-03-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_listitem_taskstardate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='taskStarDate',
            new_name='taskStartDate',
        ),
    ]
