# Generated by Django 4.0.3 on 2022-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color',
            new_name='tagColor',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskDeadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=50),
        ),
    ]
