# Generated by Django 4.0.3 on 2022-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_rename_color_tag_tagcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='taskDeadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskStartDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
