# Generated by Django 4.0.3 on 2022-03-17 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_alter_listitem_taskdeadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='taskDeadline',
        ),
        migrations.AddField(
            model_name='listitem',
            name='taskEndDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='taskEndTime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='taskStartTime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='taskStartDate',
            field=models.DateField(blank=True),
        ),
    ]
